/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

int *
suma_1_svc(struct datos *argp, struct svc_req *rqstp)
{
	static int  result;

    printf("Datos ingresados: %d y %d",argp->a, argp->b);
    result = argp->a + argp->b;
    printf("La suma es: %d", result);

	return &result;
}

int *
resta_2_svc(struct datos *argp, struct svc_req *rqstp)
{
	static int  result;
    printf("Datos ingresados: %d y %d",argp->a, argp->b);
    result = argp->a - argp->b;
    printf("La resta es: %d", result);


	return &result;
}

int *
multiplicacion_3_svc(struct datos *argp, struct svc_req *rqstp)
{
	static int  result;

    printf("Datos ingresados: %d y %d",argp->a, argp->b);
    result = argp->a * argp->b;
    printf("La multipñicacion es: %d", result);

	return &result;
}

int *
division_4_svc(struct datos *argp, struct svc_req *rqstp)
{
	static int  result;

    printf("Datos ingresados: %d y %d",argp->a, argp->b);
    result = argp->a / argp->b;
    printf("La division es: %d", result);

	return &result;
}
